spring.application.name=backend

# Database configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key
security.jwt.secret-key=${JWT_SECRET_KEY}
security.jwt.expiration-time=${JWT_EXPIRATION_TIME}
security.jwt.refresh-token-expiration-time=${JWT_REFRESH_TOKEN_EXPIRATION_TIME}

# Mail properties
spring.mail.host=${SPRING_MAIL_HOST}
spring.mail.port=${SPRING_MAIL_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# S3 (Selectel)
selectel.s3.access-key=${SELECTEL_S3_ACCESS_KEY}
selectel.s3.secret-key=${SELECTEL_S3_SECRET_KEY}
selectel.s3.endpoint=${SELECTEL_S3_ENDPOINT}
selectel.s3.region=${SELECTEL_S3_REGION}
selectel.s3.bucket-name=${SELECTEL_S3_BUCKET_NAME}
selectel.s3.domain-name=${SELECTEL_S3_DOMAIN_NAME}

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2000MB
spring.servlet.multipart.max-request-size=2000MB
server.http2.enabled=true

# Swagger-ui
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

spring.config.import=optional:file:.env[.properties]